# Disable pvp damage for tag players
cancelPVPDamage: true

# Sound played to players when someone is tagged 
# see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
tagSound: BLOCK_NOTE_BLOCK_CHIME

# Show debugging info in console
debug: false

# Various messages to palyers duting game
messages:
   prefix: '[SimpleTag] '
   no_console: 'Sorry, you must be a player to run this command.'
   already_playing: 'You are already playing a game of tag!'
   leave: 'You have left the game!'
   stop: 'The game has stopped!'
   no_game: 'Cannot find the game you requested.'
   not_online: 'That player is not online!'
   joined: 'You have joined the game!'
   started: 'Your tag game has started! Invite players to join! /stag join <yourname>'
   tagged: ' has been tagged!'
   is_it: ' is now it!'
   has_left: ' has left he game!'
   no_perm: 'You need to have permission for that command!'
   kicked: 'You have been kicked from the game of tag!'